version: '3'

services:
  nogobk:
    build: '../.'
    environment:
      - "DATABASE_USER=nogobk"
      - "DATABASE_PASSWORD=N0g0bAck"
      - "DATABASE_DB=nogobk"
      - "DATABASE_PORT=5432"
      - "DATABASE_HOST=database"
      - "DATABASE_SSL=disable"
    ports:
      - "8080:80"
    depends_on:
      - database

  database:
    image: 'postgres:11'
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=nogobk"
      - "POSTGRES_PASSWORD=N0g0bAck"
      - "POSTGRES_DB=nogobk"
    restart: unless-stopped